package com.example.shopsafe.ui.screens

import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.shopsafe.data.models.DriverTaxDocument
import com.example.shopsafe.data.models.YearEndTaxPackage
import com.example.shopsafe.ui.ShopSafeViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DriverEarningsAndTaxCenterScreen(
    viewModel: ShopSafeViewModel,
    onClose: () -> Unit,
    onOpenExpenseTracker: () -> Unit
) {
    var selectedTaxYear by remember { mutableIntStateOf(2026) }
    var showFreeFilingModal by remember { mutableStateOf(false) }
    var showGenerateYearEndPackageModal by remember { mutableStateOf(false) }
    var isPackageGenerated by remember { mutableStateOf(false) }

    val grossEarnings = 14250.00
    val tipEarnings = 3840.50
    val totalGross = grossEarnings + tipEarnings // $18,090.50
    val activeDeliveryMiles = 4280.0
    val standardMileageRate = 0.67
    val mileageDeduction = activeDeliveryMiles * standardMileageRate // $2,867.60
    val recordedExpenses = 842.24
    val estimatedTaxableIncome = totalGross - mileageDeduction - recordedExpenses // $14,380.66

    val taxDocuments = remember {
        listOf(
            DriverTaxDocument(id = "doc_1", title = "2025 Form 1099-NEC (Nonemployee Compensation)", documentType = "1099_NEC", taxYear = 2025, fileUrl = "https://shopsafe.app/tax/1099_2025.pdf"),
            DriverTaxDocument(id = "doc_2", title = "2025 Annual Mileage & Delivery Summary", documentType = "MILEAGE_SUMMARY", taxYear = 2025, fileUrl = "https://shopsafe.app/tax/miles_2025.pdf"),
            DriverTaxDocument(id = "doc_3", title = "2026 Q1 & Q2 Quarterly Estimated Tax Worksheet", documentType = "QUARTERLY_REPORT", taxYear = 2026, fileUrl = "https://shopsafe.app/tax/q2_2026.pdf")
        )
    }

    Scaffold(
        topBar = {
            Surface(
                color = Color(0xFF0F172A),
                shadowElevation = 4.dp
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .statusBarsPadding()
                ) {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(horizontal = 16.dp, vertical = 12.dp),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            IconButton(onClick = onClose) {
                                Icon(Icons.Default.ArrowBack, contentDescription = "Back", tint = Color.White)
                            }
                            Spacer(modifier = Modifier.width(4.dp))
                            Column {
                                Text(
                                    text = "Earnings & Tax Center",
                                    color = Color.White,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 17.sp
                                )
                                Text(
                                    text = "1099 Courier tax records, IRS mileage & deductions",
                                    color = Color(0xFF94A3B8),
                                    fontSize = 11.sp
                                )
                            }
                        }

                        Surface(
                            color = Color(0xFF1E293B),
                            shape = RoundedCornerShape(8.dp)
                        ) {
                            Row(
                                modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Text("Tax Year: $selectedTaxYear", color = Color(0xFF38BDF8), fontSize = 12.sp, fontWeight = FontWeight.Bold)
                            }
                        }
                    }
                }
            }
        },
        containerColor = Color(0xFF020617)
    ) { innerPadding ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Free Tax Filing Help Hero Banner
            item {
                Card(
                    shape = RoundedCornerShape(16.dp),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFF064E3B)),
                    border = BorderStroke(1.dp, Color(0xFF10B981)),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Surface(
                                shape = CircleShape,
                                color = Color(0xFF10B981),
                                modifier = Modifier.size(36.dp)
                            ) {
                                Box(contentAlignment = Alignment.Center) {
                                    Icon(Icons.Default.CardGiftcard, contentDescription = null, tint = Color.White, modifier = Modifier.size(20.dp))
                                }
                            }
                            Spacer(modifier = Modifier.width(12.dp))
                            Column(modifier = Modifier.weight(1f)) {
                                Text("Free Tax Filing for ShopSafe Drivers", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 15.sp)
                                Text("Active couriers qualify for 100% free federal and state 1099 tax filing assistance.", color = Color(0xFF6EE7B7), fontSize = 12.sp)
                            }
                        }

                        Button(
                            onClick = { showFreeFilingModal = true },
                            colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF10B981)),
                            shape = RoundedCornerShape(10.dp),
                            modifier = Modifier
                                .fillMaxWidth()
                                .testTag("free_tax_filing_button")
                        ) {
                            Text("Claim Free Filing Assistance", fontWeight = FontWeight.Bold, color = Color.White)
                        }
                    }
                }
            }

            // Year-to-Date Financial Overview Card
            item {
                Card(
                    shape = RoundedCornerShape(16.dp),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFF0F172A)),
                    border = BorderStroke(1.dp, Color(0xFF1E293B)),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text("Year-to-Date Tax Summary ($selectedTaxYear)", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 15.sp)
                            Surface(color = Color(0xFF1E293B), shape = RoundedCornerShape(6.dp)) {
                                Text("1099-NEC Form", color = Color(0xFF94A3B8), fontSize = 11.sp, modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp))
                            }
                        }

                        Divider(color = Color(0xFF1E293B))

                        // Row 1: Gross Platform Payouts
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Gross Courier Deliveries:", color = Color(0xFF94A3B8), fontSize = 13.sp)
                            Text("$${String.format("%.2f", grossEarnings)}", color = Color.White, fontWeight = FontWeight.SemiBold, fontSize = 13.sp)
                        }

                        // Row 2: Customer Tips
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Customer Tips (100% Retained):", color = Color(0xFF94A3B8), fontSize = 13.sp)
                            Text("$${String.format("%.2f", tipEarnings)}", color = Color.White, fontWeight = FontWeight.SemiBold, fontSize = 13.sp)
                        }

                        // Subtotal
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Total Gross Earnings:", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                            Text("$${String.format("%.2f", totalGross)}", color = Color(0xFF34D399), fontWeight = FontWeight.ExtraBold, fontSize = 15.sp)
                        }

                        Divider(color = Color(0xFF1E293B))

                        // Row 3: Automated IRS Mileage Deduction
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Column {
                                Text("IRS Delivery Mileage Deduction:", color = Color(0xFF38BDF8), fontWeight = FontWeight.Medium, fontSize = 13.sp)
                                Text("${String.format("%.1f", activeDeliveryMiles)} delivery miles @ $0.67/mi", color = Color(0xFF64748B), fontSize = 11.sp)
                            }
                            Text("-$${String.format("%.2f", mileageDeduction)}", color = Color(0xFF38BDF8), fontWeight = FontWeight.Bold, fontSize = 14.sp)
                        }

                        // Row 4: Recorded Expenses
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Column {
                                Text("Recorded Potential Expenses:", color = Color(0xFF94A3B8), fontSize = 13.sp)
                                Text("Tolls, parking, gear & phone allocation", color = Color(0xFF64748B), fontSize = 11.sp)
                            }
                            Text("-$${String.format("%.2f", recordedExpenses)}", color = Color(0xFF94A3B8), fontWeight = FontWeight.SemiBold, fontSize = 13.sp)
                        }

                        Divider(color = Color(0xFF1E293B))

                        // Net Estimated Taxable Earnings
                        Surface(
                            color = Color(0xFF1E293B),
                            shape = RoundedCornerShape(10.dp),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Row(
                                modifier = Modifier.padding(12.dp),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Column {
                                    Text("Estimated Taxable Courier Net:", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 13.sp)
                                    Text("After mileage & business expense write-offs", color = Color(0xFF94A3B8), fontSize = 10.sp)
                                }
                                Text("$${String.format("%.2f", estimatedTaxableIncome)}", color = Color(0xFF34D399), fontWeight = FontWeight.ExtraBold, fontSize = 18.sp)
                            }
                        }

                        // CPA Disclaimer Note
                        Text(
                            text = "⚖️ Tax Disclaimer: ShopSafe is a technology platform and not a CPA, licensed tax advisor, or legal firm. Deductions shown are organized estimates. Please consult a qualified tax professional to review your Schedule C and appropriate deduction methods.",
                            color = Color(0xFF64748B),
                            fontSize = 10.sp,
                            lineHeight = 13.sp
                        )
                    }
                }
            }

            // Action Buttons: Expense Tracker & Year-End Package
            item {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    OutlinedButton(
                        onClick = onOpenExpenseTracker,
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                            .weight(1f)
                            .height(48.dp)
                    ) {
                        Icon(Icons.Default.Receipt, contentDescription = null, tint = Color(0xFF38BDF8), modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text("Expense Tracker", color = Color(0xFF38BDF8), fontWeight = FontWeight.Bold, fontSize = 12.sp)
                    }

                    Button(
                        onClick = { showGenerateYearEndPackageModal = true },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF0284C7)),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                            .weight(1.2f)
                            .height(48.dp)
                    ) {
                        Icon(Icons.Default.FolderZip, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text("Year-End Tax Package", fontWeight = FontWeight.Bold, fontSize = 12.sp)
                    }
                }
            }

            // Tax Documents & Forms Section
            item {
                Text("Official Tax Forms & Summaries", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 16.sp)
            }

            items(taxDocuments.size) { index ->
                val doc = taxDocuments[index]
                Card(
                    shape = RoundedCornerShape(12.dp),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFF0F172A)),
                    border = BorderStroke(1.dp, Color(0xFF1E293B)),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Row(
                        modifier = Modifier.padding(14.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Surface(
                            shape = CircleShape,
                            color = Color(0xFF0284C7).copy(alpha = 0.2f),
                            modifier = Modifier.size(40.dp)
                        ) {
                            Box(contentAlignment = Alignment.Center) {
                                Icon(Icons.Default.Description, contentDescription = null, tint = Color(0xFF38BDF8), modifier = Modifier.size(20.dp))
                            }
                        }
                        Spacer(modifier = Modifier.width(12.dp))
                        Column(modifier = Modifier.weight(1f)) {
                            Text(doc.title, color = Color.White, fontWeight = FontWeight.Bold, fontSize = 13.sp)
                            Text("Official Document • Tax Year ${doc.taxYear} (${doc.fileSizeFormatted})", color = Color(0xFF94A3B8), fontSize = 11.sp)
                        }
                        IconButton(
                            onClick = {
                                // Download PDF
                            }
                        ) {
                            Icon(Icons.Default.Download, contentDescription = "Download", tint = Color(0xFF10B981))
                        }
                    }
                }
            }
        }
    }

    // Modal: Free Tax Filing Assistance
    if (showFreeFilingModal) {
        AlertDialog(
            onDismissRequest = { showFreeFilingModal = false },
            title = {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Default.VerifiedUser, contentDescription = null, tint = Color(0xFF10B981), modifier = Modifier.size(22.dp))
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Free Tax Filing for Couriers", fontWeight = FontWeight.Bold)
                }
            },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    Text("ShopSafe partners with IRS Free File and certified tax preparation providers to give couriers 100% free federal and state 1099 tax filing.", fontSize = 13.sp)
                    Surface(
                        color = Color(0xFFF1F5F9),
                        shape = RoundedCornerShape(8.dp),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Column(modifier = Modifier.padding(10.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                            Text("Included in Free Assistance:", fontWeight = FontWeight.Bold, fontSize = 12.sp)
                            Text("• 100% Free Federal & State Returns", fontSize = 12.sp)
                            Text("• Schedule C & 1099-NEC deduction optimization", fontSize = 12.sp)
                            Text("• Automatic import of ShopSafe earnings & mileage", fontSize = 12.sp)
                            Text("• Audit defense guarantee", fontSize = 12.sp)
                        }
                    }
                }
            },
            confirmButton = {
                Button(
                    onClick = { showFreeFilingModal = false },
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF10B981))
                ) {
                    Text("Start Free Filing")
                }
            },
            dismissButton = {
                TextButton(onClick = { showFreeFilingModal = false }) {
                    Text("Close")
                }
            }
        )
    }

    // Modal: Generate Year-End Package
    if (showGenerateYearEndPackageModal) {
        AlertDialog(
            onDismissRequest = { showGenerateYearEndPackageModal = false },
            title = { Text("Generate Year-End Tax Package", fontWeight = FontWeight.Bold) },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text("Compiles your complete $selectedTaxYear driver tax documentation into a single organized archive:", fontSize = 13.sp)
                    Text("• Form 1099-NEC Nonemployee Compensation\n• IRS Standard Mileage Log & Map Coordinates Certificate\n• Categorized Schedule C Business Expense Report\n• High-Resolution Original Receipt Archive", fontSize = 12.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
            },
            confirmButton = {
                Button(
                    onClick = {
                        isPackageGenerated = true
                        showGenerateYearEndPackageModal = false
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF0284C7))
                ) {
                    Text("Download ZIP Archive")
                }
            },
            dismissButton = {
                TextButton(onClick = { showGenerateYearEndPackageModal = false }) {
                    Text("Cancel")
                }
            }
        )
    }
}
